# Generated by Django 4.2 on 2023-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
